### ISSUE TITLE
Select group with drag and drop

### ISSUE THREAD

**Issue by MFalappa** [MFalappa/Phenopy3#1]
Select the subjects to be analyzed by drag and drop. When the subjects are inside the specific toolbox, give to the user the possibility to create groups with their name. Then pass datasets and labels to the selected analysis

**Comment by MFalappa** [comment]
Set the enabling of the toolbox for the integrative analyzes. Inside the toolbox, using the drug and drop tool, set the pairing of the datasets. Then move on to the selected analysis

**Comment by BalzaniEdoardo** [comment]
Wella matte, ci lavoro da oggi, scrivo in classes la classe della tabella. Direi analysis classes
